services:
    exchange.directory:
        class: iikoExchangeBundle\Service\ExchangeDirectory
        public: true

    exchange.manager:
        class: iikoExchangeBundle\Service\ExchangeManager
        public: true
        arguments: [ '@exchange.storage.preview' ,'@exchange.storage.config', '@exchange.storage.mapping', '@event_dispatcher', '@logger', '@translator' ]
        calls:
            - [ setIsDebug, [ '%kernel.debug%' ] ]

    exchange.storage.config:
        class: iikoExchangeBundle\Service\Storage\DummyConfigStorage

    exchange.storage.mapping:
        class: iikoExchangeBundle\Service\Storage\DummyMappingStorage

    exchange.storage.session:
        class: iikoExchangeBundle\Service\Storage\DummyConnectionSessionStorage

    exchange.storage.preview:
        class: iikoExchangeBundle\Service\Storage\DummyPreviewStorage

    exchange.connection.iiko:
        class: iikoExchangeBundle\Connection\iiko\iikoConnection
        arguments: [ '@logger' ]
        calls:
            - [ setServer, [ '%exchange_iiko_server%' ] ]
            - [ setUserName, [ '%exchange_iiko_username%' ] ]
            - [ setPassword, [ '%exchange_iiko_password%' ] ]


    exchange.options_sets:
        class: iikoExchangeBundle\Service\OptionSetDirectory
        public: true

    exchange.option_set_manager:
        class: iikoExchangeBundle\Service\OptionSetManager
        public: true
        arguments: [ '@logger', '@exchange.storage.config', '@exchange.options_sets' ]
    # connections

    exchange.connection.ftp:
        class: iikoExchangeBundle\Connection\Ftp\FtpConnection
        arguments: [ "CONNECTION_SFTP" ]

    exchange.connection.sftp:
        class: iikoExchangeBundle\Connection\Ftp\SftpConnection
        arguments: [ "CONNECTION_SFTP" ]

    exchange.storage.employee:
        class: iikoExchangeBundle\Service\Storage\iiko\EmployeeStorage
        arguments: ['@logger', '@exchange.connection.iiko']

    exchange.storage.schedule:
        class: iikoExchangeBundle\Service\Storage\iiko\ScheduleStorage
        arguments: ['@logger', '@exchange.connection.iiko']

    # schedulers
    exchange.schedule.cron:
        class: iikoExchangeBundle\Library\Schedule\ScheduleCron

    exchange.schedule.forecast:
        class: iikoExchangeBundle\Library\Schedule\SalesForecastingSchedule

imports:
    - { resource: option-sets.yml }
