services:
    exchange.directory:
        class: iikoExchangeBundle\Service\ExchangeDirectoryService


    exchange.manager:
        class: iikoExchangeBundle\Service\ExchangeManager
        arguments: [ '@exchange.directory','@exchange.storage.preview' ,'@exchange.storage.config', '@exchange.storage.mapping', '@event_dispatcher', '@logger', '@translator' ]

    exchange.storage.config:
        class: iikoExchangeBundle\Service\Storage\DummyConfigStorage

    exchange.storage.mapping:
        class: iikoExchangeBundle\Service\Storage\DummyMappingStorage

    exchange.storage.preview:
        class: iikoExchangeBundle\Service\Storage\DummyPreviewStorage
    exchange.connection.iiko.olap:
        class: iikoExchangeBundle\Connection\iiko\iikoConnection
        arguments: [ '@logger' ]
        calls:
            - [ setServer, [ '%exchange_iiko_server%' ] ]
            - [ setUserName, [ '%exchange_iiko_username%' ] ]
            - [ setPassword, [ '%exchange_iiko_password%' ] ]


    # connections

    exchange.connection.sftp:
        class: iikoExchangeBundle\Connection\Ftp\SftpConnection
        arguments: [ "CONNECTION_SFTP" ]

    # schedulers
    exchange.schedule.cron:
        class: iikoExchangeBundle\Library\Schedule\ScheduleCronWithPeriod